#!/bin/bash
# Echo commands for testing
#export ECHO_ONE=echo
#export ECHO_TWO=echo

# Get the location of the modified template (needed to fix a bug in markdown processing)

create_if_absent()
{
  if [ ! -d "${1}" ]
  then
    ${ECHO_TWO} mkdir -p "${1}"
  fi
}

generate_docs_for_one_file()
{
  file_base="${1:-account}"
  folder_base="${2:-token/}"
  folder_parent="${3:-state/}"
  sub_path="${folder_parent}${folder_base}"
  docs_folder="../documents/"

  create_if_absent ../documents/${sub_path}
  create_if_absent ../documents/html/${sub_path}
 
  ${ECHO_TWO} protoc --plugin=${HOME}/go/bin/protoc-gen-doc --doc_opt=${docs_folder}modified_md.tmpl,${file_base}.md --doc_out=${docs_folder}${sub_path} ${sub_path}${file_base}.proto
## Not running html as the output is quite bad.  Keeping in the script in cast it's required later.
#  ${ECHO_TWO} protoc --plugin=${HOME}/go/bin/protoc-gen-doc --doc_opt=html,${file_base}.html --doc_out=${docs_folder}html/${sub_path} ${sub_path}${file_base}.proto
}

generate_doc_set()
{
  current_folder="${1}"
  shift
  for current_file in $*
  do
    ${ECHO_ONE} generate_docs_for_one_file "${current_file}" "${current_folder}/"
  done
}

generate_docs_for_one_file "basic_types" " " " "

generate_doc_set token account nft token_relation token staking_node_info network_staking_rewards
generate_doc_set blockrecords block_info running_hashes
generate_doc_set schedule schedule
generate_doc_set throttles throttle_usage_snapshots
generate_doc_set congestion congestion_level_starts
generate_doc_set recordcache recordcache
generate_doc_set consensus topic
generate_doc_set file file
generate_doc_set contract bytecode storage_slot
#generate_doc_set 


